# Generated by Django 3.1.4 on 2021-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn_logs', '0004_addfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('member', models.ManyToManyField(to='learn_logs.Person')),
            ],
        ),
    ]
